apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-api
  template:
    metadata:
      labels:
        app: ts-api
    spec:
      containers:
        - name: ts-api
          image: ts-api:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"